/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:3e997760-1bdd-49f9-a6a3-0001d65be168",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_5fmIUQxME",
    "aws_user_pools_web_client_id": "6mgtfg7s94cpkhk59qlfuf5q9k",
    "oauth": {},
    "aws_cognito_login_mechanism": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_appsync_graphqlEndpoint": "https://jvhn34ug7vd6fo3qsxlw3ishbm.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-grhmsf6s7vggpg6wl5tfgslibi",
    "aws_user_files_s3_bucket": "todobucket211152-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
